In [75]:
import numpy as np
import pandas as pd

In [76]:

train = pd.read_csv(r'emoji.csv',header=None)
test = pd.read_csv(r'emoji_test.csv',header=None)

In [77]:
train.head()

0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [78]:
import emoji as emoji

In [79]:

emoji_dictionary = {"0": "\u2764\uFE0F",    # :heart: prints a black instead of red heart depending on the font
                    "1": ":baseball:",
                    "2": ":beaming_face_with_smiling_eyes:",
                    "3": ":downcast_face_with_sweat:",
                    "4": ":fork_and_knife:",
                   }

https://www.geeksforgeeks.org/python-program-to-print-emojis/

In [80]:
emoji.emojize('\u2764\uFE0F')

'❤️'

In [81]:
print("\u2764")

❤


In [82]:

for e in emoji_dictionary.values():
    print(emoji.emojize(e))

❤️
⚾
😁
😓
🍴


In [83]:
data = train.values
for i in range(10):
    print(data[i][0],emoji.emojize(emoji_dictionary[str(data[i][1])]))

never talk to me again 😓
I am proud of your achievements 😁
It is the worst day in my life 😓
Miss you so much ❤️
food is life 🍴
I love you mum ❤️
Stop saying bullshit 😓
congratulations on your acceptance 😁
The assignment is too long  😓
I want to go play ⚾


In [84]:
from keras.utils import to_categorical

In [85]:
train[1].unique()

array([3, 2, 0, 4, 1], dtype=int64)

In [86]:
XT = train[0]
Xt = test[0]

YT = to_categorical(train[1])
Yt = to_categorical(test[1])


print(XT.shape)
print(Xt.shape)
print(YT.shape)
print(Yt.shape)

(132,)
(56,)
(132, 5)
(56, 5)


### Download the glove embeddings from here
https://www.kaggle.com/watts2/glove6b50dtxt

In [87]:
embeddings = {}
with open(r'C:\Users\PIYUSH\Documents/glove.6B.50d.txt',encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coeffs = np.asarray(values[1:],dtype='float32')
        
        #print(word)
        #print(coeffs)
        embeddings[word] = coeffs

In [88]:
embeddings['the']

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
      dtype=float32)

In [89]:
XT[0][0]

'n'

In [90]:
def getOutputEmbeddings(X):
    embedding_matrix_output = np.zeros((X.shape[0],10,50))
    for ix in range(X.shape[0]):
        X[ix] = X[ix].split()
        for jx in range(len(X[ix])):
            embedding_matrix_output[ix][jx] = embeddings[X[ix][jx].lower()]
            
    return embedding_matrix_output

In [74]:

emb_XT = getOutputEmbeddings(XT)
emb_Xt = getOutputEmbeddings(Xt)


AttributeError: 'list' object has no attribute 'split'

In [20]:
print(emb_XT.shape)
print(emb_Xt.shape)

(132, 10, 50)
(56, 10, 50)


In [21]:
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential

In [61]:
## model using simpleRNN

In [40]:
model = Sequential()
model.add(SimpleRNN(64,input_shape=(10,50),return_sequences=True))
model.add(Dropout(0.4))
model.add(SimpleRNN(64))
model.add(Dropout(0.3))
model.add(Dense(5))
model.add(Activation('softmax'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_12 (SimpleRNN)    (None, 10, 64)            7360      
_________________________________________________________________
dropout_11 (Dropout)         (None, 10, 64)            0         
_________________________________________________________________
simple_rnn_13 (SimpleRNN)    (None, 64)                8256      
_________________________________________________________________
dropout_12 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 325       
_________________________________________________________________
activation_4 (Activation)    (None, 5)                 0         
Total params: 15,941
Trainable params: 15,941
Non-trainable params: 0
__________________________________________________

In [60]:
## model using lstm

In [48]:
classifier = Sequential()
classifier.add(LSTM(64,input_shape=(10,50),return_sequences=True))
classifier.add(Dropout(0.4))
classifier.add(LSTM(64))
classifier.add(Dropout(0.3))
classifier.add(Dense(5))
classifier.add(Activation('softmax'))
classifier.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 10, 64)            29440     
_________________________________________________________________
dropout_15 (Dropout)         (None, 10, 64)            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_16 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 325       
_________________________________________________________________
activation_6 (Activation)    (None, 5)                 0         
Total params: 62,789
Trainable params: 62,789
Non-trainable params: 0
__________________________________________________

In [41]:

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
model.fit(emb_XT,YT,batch_size=32,epochs=40,shuffle=True,validation_split=0.1)

Train on 118 samples, validate on 14 samples
Epoch 1/40
118/118 [==============================] - 2s 15ms/sample - loss: 1.8783 - acc: 0.1949 - val_loss: 1.6886 - val_acc: 0.2143
Epoch 2/40
118/118 [==============================] - 0s 339us/sample - loss: 1.5786 - acc: 0.3136 - val_loss: 1.6956 - val_acc: 0.2857
Epoch 3/40
118/118 [==============================] - 0s 305us/sample - loss: 1.5270 - acc: 0.3305 - val_loss: 1.6693 - val_acc: 0.1429
Epoch 4/40
118/118 [==============================] - 0s 339us/sample - loss: 1.3622 - acc: 0.3983 - val_loss: 1.6130 - val_acc: 0.1429
Epoch 5/40
118/118 [==============================] - 0s 339us/sample - loss: 1.2766 - acc: 0.4746 - val_loss: 1.5129 - val_acc: 0.4286
Epoch 6/40
118/118 [==============================] - 0s 372us/sample - loss: 1.2938 - acc: 0.4576 - val_loss: 1.4135 - val_acc: 0.5000
Epoch 7/40
118/118 [==============================] - 0s 305us/sample - loss: 1.1173 - acc: 0.5593 - val_loss: 1.3348 - val_acc: 0.5714
Epoc

In [43]:
model.evaluate(emb_Xt,Yt)

56/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[1.5863640478679113, 0.53571427]

In [49]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
classifier.fit(emb_XT,YT,batch_size=32,epochs=40,shuffle=True,validation_split=0.1)

Train on 118 samples, validate on 14 samples
Epoch 1/40
118/118 [==============================] - 4s 33ms/sample - loss: 1.5784 - acc: 0.2966 - val_loss: 1.6554 - val_acc: 0.2857
Epoch 2/40
118/118 [==============================] - 0s 546us/sample - loss: 1.5345 - acc: 0.3644 - val_loss: 1.6650 - val_acc: 0.2857
Epoch 3/40
118/118 [==============================] - 0s 550us/sample - loss: 1.4907 - acc: 0.4237 - val_loss: 1.6783 - val_acc: 0.1429
Epoch 4/40
118/118 [==============================] - 0s 508us/sample - loss: 1.4540 - acc: 0.4407 - val_loss: 1.6574 - val_acc: 0.2143
Epoch 5/40
118/118 [==============================] - 0s 530us/sample - loss: 1.4045 - acc: 0.3898 - val_loss: 1.6516 - val_acc: 0.1429
Epoch 6/40
118/118 [==============================] - 0s 474us/sample - loss: 1.3522 - acc: 0.4153 - val_loss: 1.5970 - val_acc: 0.2143
Epoch 7/40
118/118 [==============================] - 0s 508us/sample - loss: 1.2968 - acc: 0.4831 - val_loss: 1.5301 - val_acc: 0.2857
Epoc

In [50]:
classifier.evaluate(emb_Xt,Yt)

56/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[1.8018328973225184, 0.58928573]

In [57]:
pred = classifier.predict_classes(emb_Xt)

In [58]:
pred

array([4, 3, 2, 2, 2, 2, 3, 2, 4, 2, 1, 2, 0, 3, 1, 3, 2, 2, 3, 2, 0, 0,
       4, 3, 3, 3, 2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 3, 2, 2, 1, 0, 0, 1,
       2, 2, 3, 2, 3, 1, 3, 0, 3, 2, 2, 3], dtype=int64)

In [59]:
for i in range(30):
    print(' '.join(Xt[i]))
    print(emoji.emojize(emoji_dictionary[str(np.argmax(Yt[i]))]))
    print(emoji.emojize(emoji_dictionary[str(pred[i])]))

I want to eat
🍴
🍴
he did not answer
😓
😓
he got a raise
😁
😁
she got me a present
❤️
😁
ha ha ha it was so funny
😁
😁
he is a good friend
❤️
😁
I am upset
❤️
😓
We had such a lovely dinner tonight
❤️
😁
where is the food
🍴
🍴
Stop making this joke ha ha ha
😁
😁
where is the ball
⚾
⚾
work is hard
😓
😁
This girl is messing with me
😓
❤️
are you serious ha ha
😁
😓
Let us go play baseball
⚾
⚾
This stupid grader is not working
😓
😓
work is horrible
😓
😁
Congratulation for having a baby
😁
😁
stop messing around
😓
😓
any suggestions for dinner
🍴
😁
I love taking breaks
❤️
❤️
you brighten my day
😁
❤️
I boiled rice
🍴
🍴
she is a bully
😓
😓
Why are you feeling bad
😓
😓
I am upset
😓
😓
I worked during my birthday
😓
😁
My grandmother is the love of my life
❤️
❤️
enjoy your break
😁
⚾
valentine day is near
❤️
😁
